In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./mdshc_hk.csv')

Experiment (1), concatenate candidate mood states from section E1 and E3 for feature building

In [3]:
mood_columns = ['E1a', 'E1b', 'E1c', 'E1d', 'E1e','E1f', 'E1g', 'E1h', 'E1i', 'E3a', 'E3b', 'E3c', 'E3d', 'E3e']
exp1 = data.loc[:, mood_columns]


In [4]:
# fill na with zeros

exp11 = exp1.copy()

for column in mood_columns:
    exp11.fillna({column: 0}, inplace=True)

In [6]:
# Demo (using factor_analyzer)
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(n_factors=2, rotation=None)
fa.fit(exp11)

FactorAnalyzer(n_factors=2, rotation=None, rotation_kwargs={})

In [7]:
fa.loadings_

array([[ 4.36692604e-01, -8.49724647e-02],
       [ 4.34129444e-01,  2.64213146e-01],
       [ 4.25203788e-01,  2.38063453e-04],
       [ 3.88808590e-01, -5.40531084e-02],
       [ 3.64252626e-01,  5.50987348e-02],
       [ 5.73493486e-01, -1.24847602e-01],
       [ 3.85405823e-01, -6.46267811e-02],
       [ 4.79083055e-01, -2.98621770e-01],
       [ 4.77448102e-01, -3.09558254e-01],
       [ 1.15182195e-01,  1.96836308e-01],
       [ 2.89694355e-01,  5.01581552e-01],
       [ 1.41006377e-01,  3.46369204e-01],
       [ 9.17412802e-02,  2.83891377e-01],
       [ 2.01991613e-01,  3.35442726e-01]])

In [8]:
fa3 = FactorAnalyzer(n_factors=3, rotation=None)
fa3.fit(exp11)
fa3.loadings_

array([[ 0.42482919,  0.04353331, -0.22563147],
       [ 0.40091991,  0.31151342,  0.02218519],
       [ 0.4058498 ,  0.10385701, -0.14637931],
       [ 0.37284735,  0.04880885, -0.15811179],
       [ 0.3435837 ,  0.13233559, -0.08910536],
       [ 0.58200004,  0.05439474, -0.35352508],
       [ 0.37783388,  0.06956472, -0.26145611],
       [ 0.578629  , -0.4464878 ,  0.28835204],
       [ 0.59529478, -0.48769175,  0.30454252],
       [ 0.10515635,  0.16115365,  0.14520615],
       [ 0.26486451,  0.44688559,  0.32404587],
       [ 0.12589916,  0.28365875,  0.25259566],
       [ 0.07905767,  0.2287882 ,  0.19916325],
       [ 0.18503836,  0.28327135,  0.23610065]])

In [9]:
fa3r = FactorAnalyzer(n_factors=3, rotation='varimax', method='principal')
fa3r.fit(exp11)
fa3r.loadings_

array([[ 0.58761948, -0.03468263,  0.10336753],
       [ 0.46857436,  0.40455996, -0.02651591],
       [ 0.55341313,  0.07916573,  0.06945273],
       [ 0.52754561, -0.00389648,  0.09304806],
       [ 0.48457411,  0.13440034,  0.01645922],
       [ 0.71102045, -0.03900684,  0.14151626],
       [ 0.58349883, -0.05054098,  0.00426455],
       [ 0.15431433,  0.04262722,  0.89017568],
       [ 0.15453136,  0.02892728,  0.89230209],
       [ 0.00230956,  0.39846818,  0.04863496],
       [ 0.13813405,  0.68580535, -0.01665968],
       [-0.0122164 ,  0.57663374,  0.00193536],
       [-0.04002472,  0.50064439, -0.01871171],
       [ 0.05073452,  0.58824192,  0.04398861]])

In [18]:
# factor1: feeling, factor2: behaviour, factor3: social interaction